# Generated by Django 3.2.6 on 2022-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='django_media', verbose_name='Фото'),
        ),
    ]
