# Generated by Django 3.2.6 on 2022-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Фото'),
        ),
    ]
